# Generated by Django 5.1 on 2024-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userconnections_user_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_connections',
            name='following',
            field=models.CharField(),
        ),
    ]
