# Generated by Django 5.1 on 2024-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_connections_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_connections',
            name='following',
            field=models.JSONField(),
        ),
    ]
